/home/alagarasanc/frappe-br/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
/home/alagarasanc/frappe-br/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
/home/alagarasanc/frappe-br/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
Exception in thread Exception in thread Thread-1Thread-1:
:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1757, in run
    self.run()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1757, in run
        self.run()pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)

  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1757, in run
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1648, in get_message
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1648, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1498, in parse_response
    if not block and not self._execute(conn, conn.can_read, timeout=timeout):
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1482, in _execute
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1498, in parse_response
    return conn.retry.call_with_retry(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1648, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1498, in parse_response
    fail(error)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    if not block and not self._execute(conn, conn.can_read, timeout=timeout):
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1482, in _execute
    if not block and not self._execute(conn, conn.can_read, timeout=timeout):
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1482, in _execute
    return conn.retry.call_with_retry(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    return conn.retry.call_with_retry(
      File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
fail(error)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1484, in <lambda>
    fail(error)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise error
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1483, in <lambda>
    raise error
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 809, in can_read
    raise error
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    lambda: command(*args, **kwargs),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 809, in can_read
    return do()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
      File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 809, in can_read
return self._parser.can_read(timeout)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 411, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 423, in read_from_socket
    return self._parser.can_read(timeout)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 411, in can_read
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 423, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    sock = self.retry.call_with_retry(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    return do()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    return self._parser.can_read(timeout)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 411, in can_read
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 677, in _connect
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 677, in _connect
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 423, in read_from_socket
    raise err
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 665, in _connect
    raise err
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 665, in _connect
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.    
sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    sock.connect(socket_address)
ConnectionRefusedError    : return _run_code(code, main_globals, None,[Errno 111] Connection refused


During handling of the above exception, another exception occurred:

  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    exec(code, run_globals)
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    main()
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    exec(code, run_globals)    
click.Group(commands=commands)(prog_name="bench")  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>

  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    main()
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    return self.main(*args, **kwargs)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    rv = self.invoke(ctx)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return self.main(*args, **kwargs)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/commands/scheduler.py", line 189, in start_worker
    start_worker(queue, quiet=quiet, rq_username=rq_username, rq_password=rq_password)
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/utils/background_jobs.py", line 224, in start_worker
Traceback (most recent call last):
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 677, in _connect
    raise err
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 665, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    click.Group(commands=commands)(prog_name="bench")
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
        Worker(queues, name=get_worker_name(queue_name)).work(logging_level=logging_level)return self.main(*args, **kwargs)

  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/rq/worker.py", line 638, in work
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    self.unsubscribe()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/rq/worker.py", line 543, in unsubscribe
    return callback(*args, **kwargs)
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/commands/scheduler.py", line 189, in start_worker
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    start_worker(queue, quiet=quiet, rq_username=rq_username, rq_password=rq_password)
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/utils/background_jobs.py", line 224, in start_worker
    self.pubsub.unsubscribe()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1617, in unsubscribe
    Worker(queues, name=get_worker_name(queue_name)).work(logging_level=logging_level)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/rq/worker.py", line 638, in work
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1443, in execute_command
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/commands/scheduler.py", line 189, in start_worker
    start_worker(queue, quiet=quiet, rq_username=rq_username, rq_password=rq_password)
  File "/home/alagarasanc/frappe-br/apps/frappe/frappe/utils/background_jobs.py", line 224, in start_worker
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1482, in _execute
    Worker(queues, name=get_worker_name(queue_name)).work(logging_level=logging_level)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/rq/worker.py", line 638, in work
    self.unsubscribe()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/rq/worker.py", line 543, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1617, in unsubscribe
    return conn.retry.call_with_retry(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1484, in <lambda>
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1443, in execute_command
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1482, in _execute
    raise error
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1483, in <lambda>
    self.unsubscribe()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/rq/worker.py", line 543, in unsubscribe
    return conn.retry.call_with_retry(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1484, in <lambda>
    self.pubsub.unsubscribe()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1617, in unsubscribe
    lambda: command(*args, **kwargs),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 799, in send_command
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    self.send_packed_command(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 773, in send_packed_command
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1443, in execute_command
    self.connect()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
    raise error
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1483, in <lambda>
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1482, in _execute
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11002. Connection refused.
    lambda: command(*args, **kwargs),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 799, in send_command
    return conn.retry.call_with_retry(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1484, in <lambda>
    self.send_packed_command(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 773, in send_packed_command
    self.connect()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11002. Connection refused.
    raise error
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 799, in send_command
    self.send_packed_command(
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 773, in send_packed_command
    self.connect()
  File "/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11002. Connection refused.
/home/alagarasanc/frappe-br/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
/home/alagarasanc/frappe-br/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
/home/alagarasanc/frappe-br/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/alagarasanc/frappe-br/env/lib/python3.10/site-packages/botocore/httpsession.py:19: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
